NICHE_CONFIGS = [
    {
        "niche_id": "finance",
        "display_name": "Finance & Investing",
        "emoji": "💰",
        "estimated_cpm_range": "$18–$65",
        "script_tone": "authoritative, data-driven, trust-building",
        "hook_style": "shocking statistic or counterintuitive fact",
        "thumbnail_colors": {
            "background": "#0a1628",
            "primary_text": "#FFFFFF",
            "accent": "#F5B400",
            "secondary": "#1E3A5F"
        },
        "thumbnail_emotion": "aspirational + urgent",
        "voiceover_style": "calm authority, measured pace",
        "music_mood": "corporate lo-fi, 70-85 BPM, no drops",
        "stock_keywords": ["stock market", "money", "investment", "wealth", "financial planning"],
        "image_prompt_style": "professional financial photography, dark moody lighting, gold accents",
        "title_formula": "[Number] [Topic] That [Outcome] in [Timeframe]",
        "recommended_duration": "10-15 minutes",
        "recommended_upload_time": "Tuesday-Thursday 2PM EST"
    },
    {
        "niche_id": "personal_finance",
        "display_name": "Personal Finance",
        "emoji": "💳",
        "estimated_cpm_range": "$15–$55",
        "script_tone": "relatable, actionable, encouraging",
        "hook_style": "common money mistake or quick win",
        "thumbnail_colors": {
            "background": "#0d1f12",
            "primary_text": "#FFFFFF",
            "accent": "#22C55E",
            "secondary": "#064E3B"
        },
        "thumbnail_emotion": "surprised but hopeful",
        "voiceover_style": "friendly, guiding, clear",
        "music_mood": "upbeat lo-fi, positive vibe",
        "stock_keywords": ["budgeting", "savings", "credit cards", "personal finance", "calculator"],
        "image_prompt_style": "clean modern desk workspace, budgeting tools, bright uplifting lighting",
        "title_formula": "How to [Achieve Goal] with [Specific Tool/Method] (Step-by-Step)",
        "recommended_duration": "8-12 minutes",
        "recommended_upload_time": "Monday 3PM EST"
    },
    {
        "niche_id": "real_estate",
        "display_name": "Real Estate",
        "emoji": "🏠",
        "estimated_cpm_range": "$20–$70",
        "script_tone": "professional, visionary, strategic",
        "hook_style": "insider secret or massive ROI claim",
        "thumbnail_colors": {
            "background": "#1e1e1e",
            "primary_text": "#FFFFFF",
            "accent": "#3B82F6",
            "secondary": "#1D4ED8"
        },
        "thumbnail_emotion": "impressed, wealthy",
        "voiceover_style": "confident, crisp, professional",
        "music_mood": "luxury corporate, smooth bass",
        "stock_keywords": ["luxury home", "real estate", "property", "house keys", "cityscape"],
        "image_prompt_style": "luxury real estate exterior, golden hour, modern architecture",
        "title_formula": "The Truth About [Real Estate Topic] in [Year]",
        "recommended_duration": "12-18 minutes",
        "recommended_upload_time": "Wednesday 12PM EST"
    },
    {
        "niche_id": "insurance",
        "display_name": "Insurance",
        "emoji": "🛡️",
        "estimated_cpm_range": "$25–$80",
        "script_tone": "cautious, informative, protective",
        "hook_style": "financial disaster story leading to prevention",
        "thumbnail_colors": {
            "background": "#171717",
            "primary_text": "#FFFFFF",
            "accent": "#EF4444",
            "secondary": "#991B1B"
        },
        "thumbnail_emotion": "serious, concerned",
        "voiceover_style": "reassuring, serious, educational",
        "music_mood": "tense documentary background, minimal melody",
        "stock_keywords": ["car accident", "hospital bill", "insurance policy", "family protection", "signing papers"],
        "image_prompt_style": "serious corporate document setting, dramatic shadows",
        "title_formula": "Don't Buy [Type of Insurance] Until You Watch This",
        "recommended_duration": "8-12 minutes",
        "recommended_upload_time": "Tuesday 10AM EST"
    },
    {
        "niche_id": "legal",
        "display_name": "Legal & Law",
        "emoji": "⚖️",
        "estimated_cpm_range": "$30–$90",
        "script_tone": "highly authoritative, exact, cautionary",
        "hook_style": "loophole exposure or legal trap warning",
        "thumbnail_colors": {
            "background": "#1e293b",
            "primary_text": "#F8FAFC",
            "accent": "#FCD34D",
            "secondary": "#0F172A"
        },
        "thumbnail_emotion": "shocked, secretive",
        "voiceover_style": "formal, deliberate, stern",
        "music_mood": "crime-doc style, slow pulsing drone",
        "stock_keywords": ["gavel", "courthouse", "lawyer", "legal documents", "justice"],
        "image_prompt_style": "dark wood textures, legal scales, moody cinematic lighting",
        "title_formula": "Why [Company/Person] is Being Sued for [Amount]",
        "recommended_duration": "15-20 minutes",
        "recommended_upload_time": "Thursday 4PM EST"
    },
    {
        "niche_id": "health_wellness",
        "display_name": "Health & Wellness",
        "emoji": "🍏",
        "estimated_cpm_range": "$12–$40",
        "script_tone": "nurturing, scientific but accessible",
        "hook_style": "myth-busting a common health belief",
        "thumbnail_colors": {
            "background": "#064E3B",
            "primary_text": "#FFFFFF",
            "accent": "#A7F3D0",
            "secondary": "#047857"
        },
        "thumbnail_emotion": "vibrant, energetic",
        "voiceover_style": "calming, enthusiastic, clear",
        "music_mood": "ambient meditation, gentle acoustic",
        "stock_keywords": ["healthy food", "yoga", "nature", "meditation", "drinking water"],
        "image_prompt_style": "fresh bright ingredients, sunlit kitchen, clean aesthetic",
        "title_formula": "What Happens to Your Body When You [Action] for [Time]",
        "recommended_duration": "10-12 minutes",
        "recommended_upload_time": "Sunday 9AM EST"
    },
    {
        "niche_id": "mental_health",
        "display_name": "Mental Health",
        "emoji": "🧠",
        "estimated_cpm_range": "$10–$35",
        "script_tone": "empathetic, validating, psychological",
        "hook_style": "describing a hidden symptom people relate to",
        "thumbnail_colors": {
            "background": "#2e1065",
            "primary_text": "#FFFFFF",
            "accent": "#D8B4FE",
            "secondary": "#4C1D95"
        },
        "thumbnail_emotion": "deep thought, realization",
        "voiceover_style": "soft, slow, empathetic",
        "music_mood": "soft sad piano, ambient sweeps",
        "stock_keywords": ["thinking", "therapy", "brain", "journaling", "comforting"],
        "image_prompt_style": "abstract mind concept, soft purple lighting, ethereal",
        "title_formula": "[Number] Signs You Have [Hidden Condition] without Knowing",
        "recommended_duration": "12-15 minutes",
        "recommended_upload_time": "Sunday 6PM EST"
    },
    {
        "niche_id": "weight_loss",
        "display_name": "Weight Loss & Fitness",
        "emoji": "💪",
        "estimated_cpm_range": "$10–$38",
        "script_tone": "motivating, intense, scientific",
        "hook_style": "diet industry secret or shocking transformation",
        "thumbnail_colors": {
            "background": "#000000",
            "primary_text": "#FFFFFF",
            "accent": "#F97316",
            "secondary": "#C2410C"
        },
        "thumbnail_emotion": "determined, energetic",
        "voiceover_style": "high energy, pushing, loud",
        "music_mood": "upbeat workout, synthwave, driven",
        "stock_keywords": ["workout", "running", "gym", "healthy meal", "weight scale"],
        "image_prompt_style": "high contrast gym lighting, sweat, intense action",
        "title_formula": "The Only [Topic] Routine You Need to Lose [Amount] in [Time]",
        "recommended_duration": "8-12 minutes",
        "recommended_upload_time": "Monday 8AM EST"
    },
    {
        "niche_id": "tech_ai",
        "display_name": "Technology & AI",
        "emoji": "🤖",
        "estimated_cpm_range": "$12–$45",
        "script_tone": "futuristic, analytical, fast-paced",
        "hook_style": "new tech threatening a major industry",
        "thumbnail_colors": {
            "background": "#000000",
            "primary_text": "#FFFFFF",
            "accent": "#06B6D4",
            "secondary": "#0891B2"
        },
        "thumbnail_emotion": "mind-blown, futuristic",
        "voiceover_style": "fast, technical but simple, excited",
        "music_mood": "cyberpunk synth wave, fast tempo",
        "stock_keywords": ["artificial intelligence", "coding", "robotics", "server room", "hologram"],
        "image_prompt_style": "glowing neon circuits, cyberpunk city, holographic interfaces",
        "title_formula": "Why [Tech] will Destroy [Industry] by [Year]",
        "recommended_duration": "10-15 minutes",
        "recommended_upload_time": "Wednesday 1PM EST"
    },
    {
        "niche_id": "crypto",
        "display_name": "Crypto & Blockchain",
        "emoji": "₿",
        "estimated_cpm_range": "$15–$60",
        "script_tone": "urgent, speculative, data-heavy",
        "hook_style": "massive price prediction or insider whale movement",
        "thumbnail_colors": {
            "background": "#2c1c0c",
            "primary_text": "#FFFFFF",
            "accent": "#F59E0B",
            "secondary": "#B45309"
        },
        "thumbnail_emotion": "panic or extreme excitement",
        "voiceover_style": "fast, urgent, confident",
        "music_mood": "tense electronic, driving beat",
        "stock_keywords": ["bitcoin", "trading charts", "cryptocurrency", "hacker", "blockchain"],
        "image_prompt_style": "golden cyber coins, glowing upward charts, neon yellow",
        "title_formula": "URGENT: [Coin] is About to do THIS (Price Prediction)",
        "recommended_duration": "10-12 minutes",
        "recommended_upload_time": "Friday 11AM EST"
    },
    {
        "niche_id": "business",
        "display_name": "Business & Entrepreneurship",
        "emoji": "📈",
        "estimated_cpm_range": "$14–$50",
        "script_tone": "strategic, case-study focused, visionary",
        "hook_style": "how a company secretly made billions",
        "thumbnail_colors": {
            "background": "#1e293b",
            "primary_text": "#FFFFFF",
            "accent": "#38BDF8",
            "secondary": "#0369A1"
        },
        "thumbnail_emotion": "strategic, successful",
        "voiceover_style": "smooth, corporate, storytelling",
        "music_mood": "inspirational corporate, building climax",
        "stock_keywords": ["office skyscraper", "handshake", "startup", "office meeting", "charts"],
        "image_prompt_style": "modern skyscraper glass, cinematic office, blue steel tones",
        "title_formula": "How [Company] Fooled the World and Made $Billion",
        "recommended_duration": "15-25 minutes",
        "recommended_upload_time": "Tuesday 1PM EST"
    },
    {
        "niche_id": "self_improvement",
        "display_name": "Self Improvement",
        "emoji": "🌱",
        "estimated_cpm_range": "$10–$35",
        "script_tone": "philosophical, harsh truth, empowering",
        "hook_style": "the harsh reality holding the viewer back",
        "thumbnail_colors": {
            "background": "#18181b",
            "primary_text": "#FFFFFF",
            "accent": "#EAB308",
            "secondary": "#854D0E"
        },
        "thumbnail_emotion": "stoic, intense",
        "voiceover_style": "slow, deep, stoic, commanding",
        "music_mood": "dark ambient, cinematic drone",
        "stock_keywords": ["man walking alone", "climbing mountain", "writing journal", "meditation", "dark silhouette"],
        "image_prompt_style": "stoic marble statue, dark background, single light source, moody",
        "title_formula": "[Number] Habits Keeping You Poor and Weak",
        "recommended_duration": "10-15 minutes",
        "recommended_upload_time": "Sunday 10AM EST"
    },
    {
        "niche_id": "motivation",
        "display_name": "Motivation & Mindset",
        "emoji": "🔥",
        "estimated_cpm_range": "$8–$30",
        "script_tone": "intense, emotional, driving",
        "hook_style": "emotional speech intro hitting rock bottom",
        "thumbnail_colors": {
            "background": "#000000",
            "primary_text": "#FFFFFF",
            "accent": "#DC2626",
            "secondary": "#7F1D1D"
        },
        "thumbnail_emotion": "screaming success, aggressive",
        "voiceover_style": "loud, passionate, echoing",
        "music_mood": "epic orchestral, massive drums",
        "stock_keywords": ["boxing", "running in rain", "screaming", "success", "winning"],
        "image_prompt_style": "silhouetted winner in rain, neon red accents, extreme contrast",
        "title_formula": "WATCH THIS CURE YOUR LAZINESS - Motivation [Year]",
        "recommended_duration": "8-10 minutes",
        "recommended_upload_time": "Monday 6AM EST"
    },
    {
        "niche_id": "history",
        "display_name": "History & Facts",
        "emoji": "📜",
        "estimated_cpm_range": "$8–$25",
        "script_tone": "documentary, mysterious, storytelling",
        "hook_style": "the dark truth they didn't teach in school",
        "thumbnail_colors": {
            "background": "#292524",
            "primary_text": "#F5F5F4",
            "accent": "#D97706",
            "secondary": "#78350F"
        },
        "thumbnail_emotion": "mysterious, uncovering",
        "voiceover_style": "classic narrator, dramatic pauses",
        "music_mood": "orchestral suspense, classical",
        "stock_keywords": ["old map", "ruins", "ancient documents", "statue", "black and white war"],
        "image_prompt_style": "sepia toned old manuscript, dramatic lighting, volumetric dust",
        "title_formula": "The Dark History of [Topic] School Lied About",
        "recommended_duration": "15-30 minutes",
        "recommended_upload_time": "Saturday 12PM EST"
    },
    {
        "niche_id": "true_crime",
        "display_name": "True Crime & Mystery",
        "emoji": "🔍",
        "estimated_cpm_range": "$8–$28",
        "script_tone": "gripping, dark, suspenseful",
        "hook_style": "the chilling 911 call or exact moment of disappearance",
        "thumbnail_colors": {
            "background": "#000000",
            "primary_text": "#FFFFFF",
            "accent": "#B91C1C",
            "secondary": "#7F1D1D"
        },
        "thumbnail_emotion": "terrified, mysterious",
        "voiceover_style": "low, whispery, suspenseful",
        "music_mood": "dark drone, heartbeat, scary",
        "stock_keywords": ["police lights", "abandoned house", "crime tape", "detective board", "shadows"],
        "image_prompt_style": "dark alleyway, glowing crime tape, heavy rain, moody red lighting",
        "title_formula": "The Unsolved Case of the [Adjective] [Noun]",
        "recommended_duration": "20-40 minutes",
        "recommended_upload_time": "Friday 8PM EST"
    },
    {
        "niche_id": "science",
        "display_name": "Science & Education",
        "emoji": "🔬",
        "estimated_cpm_range": "$8–$22",
        "script_tone": "curious, mind-bending, accessible",
        "hook_style": "a paradox or mind-blowing cosmic scale fact",
        "thumbnail_colors": {
            "background": "#020617",
            "primary_text": "#FFFFFF",
            "accent": "#8B5CF6",
            "secondary": "#4C1D95"
        },
        "thumbnail_emotion": "awe, confusion",
        "voiceover_style": "energetic, clear, inquisitive",
        "music_mood": "synth space ambient, curious",
        "stock_keywords": ["space galaxy", "microscope", "laboratory", "dna visualization", "planet"],
        "image_prompt_style": "glowing purple nebula, hyper-detailed cosmic dust, 8k",
        "title_formula": "What If [Extreme Scenario] Happened Tomorrow?",
        "recommended_duration": "12-18 minutes",
        "recommended_upload_time": "Saturday 2PM EST"
    },
    {
        "niche_id": "productivity",
        "display_name": "Productivity & Tools",
        "emoji": "⚡",
        "estimated_cpm_range": "$12–$40",
        "script_tone": "systematic, highly practical, fast",
        "hook_style": "how a new tool saves 20 hours a week",
        "thumbnail_colors": {
            "background": "#fafafa",
            "primary_text": "#000000",
            "accent": "#F43F5E",
            "secondary": "#9F1239"
        },
        "thumbnail_emotion": "clean, focused",
        "voiceover_style": "upbeat, crisp, fast-paced",
        "music_mood": "lo-fi hip hop, chillwork",
        "stock_keywords": ["typing on laptop", "coffee and notebook", "calendar", "desk setup", "coding"],
        "image_prompt_style": "aesthetic unboxing style desk setup, bright natural light, minimalist",
        "title_formula": "My [System] That Guarantees [Result] Every Day",
        "recommended_duration": "8-15 minutes",
        "recommended_upload_time": "Monday 10AM EST"
    },
    {
        "niche_id": "career",
        "display_name": "Career & Jobs",
        "emoji": "💼",
        "estimated_cpm_range": "$15–$45",
        "script_tone": "advisory, insider-knowledge, encouraging",
        "hook_style": "resume mistake 99% of candidates make",
        "thumbnail_colors": {
            "background": "#0F172A",
            "primary_text": "#FFFFFF",
            "accent": "#10B981",
            "secondary": "#047857"
        },
        "thumbnail_emotion": "confident, employed",
        "voiceover_style": "professional, guiding mentor",
        "music_mood": "subtle corporate background, positive",
        "stock_keywords": ["job interview", "shaking hands", "office building", "resume", "working late"],
        "image_prompt_style": "corporate glass office, confident handshake silhouette",
        "title_formula": "How to Pass Any [Role] Interview in [Year]",
        "recommended_duration": "10-15 minutes",
        "recommended_upload_time": "Tuesday 2PM EST"
    },
    {
        "niche_id": "relationships",
        "display_name": "Relationships & Psychology",
        "emoji": "❤️",
        "estimated_cpm_range": "$10–$32",
        "script_tone": "intimate, psychological, validating",
        "hook_style": "micro-behavior that ruins relationships",
        "thumbnail_colors": {
            "background": "#311226",
            "primary_text": "#FFFFFF",
            "accent": "#EC4899",
            "secondary": "#9D174D"
        },
        "thumbnail_emotion": "dramatic, sad or happy",
        "voiceover_style": "soft, empathetic, engaging",
        "music_mood": "soft acoustic guitar, emotional piano",
        "stock_keywords": ["couple arguing", "holding hands", "crying", "therapy couch", "smiling couple"],
        "image_prompt_style": "moody cinematic lighting, silhouette couple, dramatic shadow",
        "title_formula": "[Number] Signs They Are Secretly [Emotion/Behavior]",
        "recommended_duration": "10-12 minutes",
        "recommended_upload_time": "Thursday 7PM EST"
    },
    {
        "niche_id": "luxury",
        "display_name": "Luxury & Lifestyle",
        "emoji": "🛥️",
        "estimated_cpm_range": "$12–$42",
        "script_tone": "aspirational, exclusive, materialistic",
        "hook_style": "the hidden cost of owning a superyacht",
        "thumbnail_colors": {
            "background": "#111111",
            "primary_text": "#EAB308",
            "accent": "#FFFFFF",
            "secondary": "#49423D"
        },
        "thumbnail_emotion": "exclusive, rich",
        "voiceover_style": "smooth, expensive-sounding, relaxed",
        "music_mood": "luxury lounge house, chillout pool",
        "stock_keywords": ["yacht", "private jet", "rolex", "mansions", "dubai"],
        "image_prompt_style": "gold luxury aesthetic, private jet interior, sparkling champagne",
        "title_formula": "Inside the $Billion Life of [Person/Location]",
        "recommended_duration": "10-14 minutes",
        "recommended_upload_time": "Friday 3PM EST"
    }
]
