import { NicheConfig } from '../types';

export const niches: NicheConfig[] = [
  {
    niche_id: 'finance',
    display_name: 'Finance & Investing',
    emoji: '💰',
    tier: 'platinum',
    estimated_cpm_range: '$18–$65',
    cpm: { min: 18, max: 65 },
    script_tone: 'authoritative, data-driven',
    hook_style: 'shocking_stat',
    thumbnail_colors: { background: '#0a1628', primary_text: '#FFFFFF', accent: '#F5B400', secondary: '#1E3A5F' },
    thumbnail_emotion: 'aspirational + urgent',
    voiceover_style: 'calm authority, measured pace',
    music_mood: 'corporate lo-fi, 70-85 BPM, no drops',
    stock_keywords: ['investing', 'stocks', 'wealth', 'passive income', 'ETF'],
    image_prompt_style: 'professional financial photography, dark moody lighting, gold accents',
    title_formula: '[Number] [Topic] That [Outcome] in [Timeframe]',
    recommended_duration: '8-12 minutes',
    recommendedDuration: [480, 720],
    recommended_upload_time: 'Tuesday-Thursday 2PM EST',
    platforms: { youtube: { score: 10, note: "Highest RPM platform" }, tiktok: { score: 6, note: "Works but lower CPM" }, shorts: { score: 7, note: "Good for lead gen" } },
    bestStyles: ["cinematic", "whiteboard", "infographic"],
    avoidStyles: ["ghibli", "paper_craft"],
    hookFormulas: ["shocking_stat", "bold_claim", "curiosity_gap"],
    keywords: ["investing", "stocks", "wealth", "passive income", "ETF"],
    monetization: ["AdSense", "sponsorships", "affiliate (broker)"],
    contentPillars: ["market news", "how-to invest", "portfolio review", "stock picks", "ETF & index funds", "dividend investing", "options trading", "Warren Buffett strategies", "bear market survival", "passive income", "IPO breakdowns", "hedge fund secrets"],
    audience: { age: "25–45", intent: "high buying", retention: "high" },
    competitionLevel: "high"
  },
  {
    niche_id: 'insurance',
    display_name: 'Insurance',
    emoji: '🛡️',
    tier: 'platinum',
    estimated_cpm_range: '$25–$80',
    cpm: { min: 25, max: 80 },
    script_tone: 'calm, trustworthy, educational',
    hook_style: 'fear_hook',
    thumbnail_colors: { background: '#171717', primary_text: '#FFFFFF', accent: '#EF4444', secondary: '#991B1B' },
    thumbnail_emotion: 'serious, concerned',
    voiceover_style: 'reassuring, serious, educational',
    music_mood: 'tense documentary background, minimal melody',
    stock_keywords: ['life insurance', 'health coverage', 'term vs whole'],
    image_prompt_style: 'serious corporate document setting, dramatic shadows',
    title_formula: "Don't Buy [Type of Insurance] Until You Watch This",
    recommended_duration: '6-10 minutes',
    recommendedDuration: [360, 600],
    recommended_upload_time: 'Tuesday 10AM EST',
    platforms: { youtube: { score: 10, note: "Best CPM niche on YouTube" }, tiktok: { score: 4, note: "Avoid — audience mismatch" } },
    bestStyles: ["cinematic", "whiteboard", "3d_render"],
    avoidStyles: ["ghibli", "dark_noir", "pov"],
    hookFormulas: ["fear_hook", "shocking_stat", "question_hook"],
    keywords: ["life insurance", "health coverage", "term vs whole"],
    monetization: ["AdSense", "lead gen", "affiliate"],
    contentPillars: ["explainers", "comparisons", "mistakes to avoid", "life insurance", "health insurance", "car insurance", "home insurance", "term vs whole", "insurance scams", "best policies 2025", "what NOT to buy"],
    audience: { age: "30–55", intent: "very high buying", retention: "medium" },
    competitionLevel: "medium"
  },
  {
    niche_id: 'legal',
    display_name: 'Legal & Law',
    emoji: '⚖️',
    tier: 'platinum',
    estimated_cpm_range: '$30–$90',
    cpm: { min: 30, max: 90 },
    script_tone: 'serious, authoritative',
    hook_style: 'fear_hook',
    thumbnail_colors: { background: '#1e293b', primary_text: '#F8FAFC', accent: '#FCD34D', secondary: '#0F172A' },
    thumbnail_emotion: 'shocked, secretive',
    voiceover_style: 'formal, deliberate, stern',
    music_mood: 'crime-doc style, slow pulsing drone',
    stock_keywords: ['lawsuit', 'legal rights', 'attorney', 'court'],
    image_prompt_style: 'dark wood textures, legal scales, moody cinematic lighting',
    title_formula: 'Why [Company/Person] is Being Sued for [Amount]',
    recommended_duration: '8-15 minutes',
    recommendedDuration: [480, 900],
    recommended_upload_time: 'Thursday 4PM EST',
    platforms: { youtube: { score: 10, note: "Highest CPM possible" }, shorts: { score: 6, note: "Great for awareness" } },
    bestStyles: ["cinematic", "whiteboard", "documentary"],
    avoidStyles: ["ghibli", "paper_craft", "pov"],
    hookFormulas: ["fear_hook", "bold_claim", "story_open"],
    keywords: ["lawsuit", "legal rights", "attorney", "court"],
    monetization: ["AdSense", "legal firm sponsorship", "consultations"],
    contentPillars: ["know your rights", "case breakdowns", "legal myths", "employee rights", "landlord-tenant law", "divorce law", "criminal defense", "small claims court", "contract traps", "immigration law", "police encounters", "sue your employer"],
    audience: { age: "28–55", intent: "high", retention: "high" },
    competitionLevel: "low"
  },
  {
    niche_id: 'real_estate',
    display_name: 'Real Estate',
    emoji: '🏠',
    tier: 'platinum',
    estimated_cpm_range: '$20–$70',
    cpm: { min: 20, max: 70 },
    script_tone: 'confident, aspirational',
    hook_style: 'curiosity_gap',
    thumbnail_colors: { background: '#1e1e1e', primary_text: '#FFFFFF', accent: '#3B82F6', secondary: '#1D4ED8' },
    thumbnail_emotion: 'impressed, wealthy',
    voiceover_style: 'confident, crisp, professional',
    music_mood: 'luxury corporate, smooth bass',
    stock_keywords: ['real estate investing', 'rental property', 'house flipping'],
    image_prompt_style: 'luxury real estate exterior, golden hour, modern architecture',
    title_formula: 'The Truth About [Real Estate Topic] in [Year]',
    recommended_duration: '8-12 minutes',
    recommendedDuration: [480, 720],
    recommended_upload_time: 'Wednesday 12PM EST',
    platforms: { youtube: { score: 9, note: "Strong long-form" }, reels: { score: 8, note: "Property tours go viral" } },
    bestStyles: ["cinematic", "3d_render", "documentary"],
    avoidStyles: ["ghibli", "whiteboard"],
    hookFormulas: ["curiosity_gap", "bold_claim", "shocking_stat"],
    keywords: ["real estate investing", "rental property", "house flipping"],
    monetization: ["AdSense", "course sales", "agent referrals"],
    contentPillars: ["market analysis", "how to buy", "investing tips", "house flipping", "rental property", "short-term rentals", "REITs explained", "real estate mistakes", "first-time buyer guide", "commercial real estate", "real estate in 2025", "passive income from property"],
    audience: { age: "28–50", intent: "very high", retention: "high" },
    competitionLevel: "high"
  },
  {
    niche_id: 'personal_finance',
    display_name: 'Personal Finance',
    emoji: '💳',
    tier: 'gold',
    estimated_cpm_range: '$15–$55',
    cpm: { min: 15, max: 55 },
    script_tone: 'relatable, practical',
    hook_style: 'shocking_stat',
    thumbnail_colors: { background: '#0d1f12', primary_text: '#FFFFFF', accent: '#22C55E', secondary: '#064E3B' },
    thumbnail_emotion: 'surprised but hopeful',
    voiceover_style: 'friendly, guiding, clear',
    music_mood: 'upbeat lo-fi, positive vibe',
    stock_keywords: ['budgeting', 'saving money', 'debt free', 'frugal'],
    image_prompt_style: 'clean modern desk workspace, budgeting tools, bright uplifting lighting',
    title_formula: 'How to [Achieve Goal] with [Specific Tool/Method] (Step-by-Step)',
    recommended_duration: '5-10 minutes',
    recommendedDuration: [300, 600],
    recommended_upload_time: 'Monday 3PM EST',
    platforms: { youtube: { score: 9, note: "Evergreen content" }, tiktok: { score: 7, note: "Budget tips go viral" }, shorts: { score: 8, note: "Quick tips format" } },
    bestStyles: ["whiteboard", "infographic", "cinematic"],
    avoidStyles: ["dark_noir", "ghibli"],
    hookFormulas: ["shocking_stat", "question_hook", "curiosity_gap"],
    keywords: ["budgeting", "saving money", "debt free", "frugal"],
    monetization: ["AdSense", "affiliate (credit cards)", "course"],
    contentPillars: ["budgeting", "saving hacks", "debt payoff", "frugality", "emergency fund", "credit score", "side hustles", "spend less", "financial freedom", "money mistakes", "50/30/20 rule", "zero-based budgeting"],
    audience: { age: "20–40", intent: "high", retention: "medium" },
    competitionLevel: "very high"
  },
  {
    niche_id: 'crypto',
    display_name: 'Crypto & Blockchain',
    emoji: '₿',
    tier: 'gold',
    estimated_cpm_range: '$15–$60',
    cpm: { min: 15, max: 60 },
    script_tone: 'energetic, forward-looking',
    hook_style: 'bold_claim',
    thumbnail_colors: { background: '#2c1c0c', primary_text: '#FFFFFF', accent: '#F59E0B', secondary: '#B45309' },
    thumbnail_emotion: 'panic or extreme excitement',
    voiceover_style: 'fast, urgent, confident',
    music_mood: 'tense electronic, driving beat',
    stock_keywords: ['Bitcoin', 'crypto portfolio', 'altcoins', 'DeFi'],
    image_prompt_style: 'golden cyber coins, glowing upward charts, neon yellow',
    title_formula: 'URGENT: [Coin] is About to do THIS (Price Prediction)',
    recommended_duration: '5-12 minutes',
    recommendedDuration: [300, 720],
    recommended_upload_time: 'Friday 11AM EST',
    platforms: { youtube: { score: 9, note: "Strong community" }, tiktok: { score: 8, note: "Viral during bull runs" } },
    bestStyles: ["cinematic", "3d_render", "dark_noir"],
    avoidStyles: ["watercolor", "paper_craft"],
    hookFormulas: ["bold_claim", "controversy", "curiosity_gap"],
    keywords: ["Bitcoin", "crypto portfolio", "altcoins", "DeFi"],
    monetization: ["AdSense", "exchange affiliate", "token sponsorship"],
    contentPillars: ["market analysis", "coin reviews", "crypto news", "tutorials", "Bitcoin predictions", "altcoin gems", "DeFi explained", "NFT market", "crypto wallet setup", "on-chain analysis", "exchange comparison", "crypto tax guide"],
    audience: { age: "18–40", intent: "high", retention: "medium" },
    competitionLevel: "very high"
  },
  {
    niche_id: 'tech_ai',
    display_name: 'Technology & AI',
    emoji: '🤖',
    tier: 'gold',
    estimated_cpm_range: '$12–$45',
    cpm: { min: 12, max: 45 },
    script_tone: 'informative, excited',
    hook_style: 'curiosity_gap',
    thumbnail_colors: { background: '#000000', primary_text: '#FFFFFF', accent: '#06B6D4', secondary: '#0891B2' },
    thumbnail_emotion: 'mind-blown, futuristic',
    voiceover_style: 'fast, technical but simple, excited',
    music_mood: 'cyberpunk synth wave, fast tempo',
    stock_keywords: ['AI tools', 'ChatGPT', 'automation', 'future of tech'],
    image_prompt_style: 'glowing neon circuits, cyberpunk city, holographic interfaces',
    title_formula: 'Why [Tech] will Destroy [Industry] by [Year]',
    recommended_duration: '6-12 minutes',
    recommendedDuration: [360, 720],
    recommended_upload_time: 'Wednesday 1PM EST',
    platforms: { youtube: { score: 10, note: "Best long-form niche" }, shorts: { score: 9, note: "Tool demos go viral" }, tiktok: { score: 7, note: "Works for AI tools" } },
    bestStyles: ["3d_render", "cinematic", "infographic"],
    avoidStyles: ["watercolor", "paper_craft", "pov"],
    hookFormulas: ["curiosity_gap", "bold_claim", "shocking_stat"],
    keywords: ["AI tools", "ChatGPT", "automation", "future of tech"],
    monetization: ["AdSense", "SaaS affiliate", "tool sponsorship"],
    contentPillars: ["tool reviews", "tutorials", "AI news", "predictions", "ChatGPT tips", "AI automation", "best AI tools", "prompt engineering", "AI vs humans", "future of jobs", "robotics", "machine learning explained"],
    audience: { age: "20–45", intent: "high", retention: "very high" },
    competitionLevel: "high"
  },
  {
    niche_id: 'business',
    display_name: 'Business & Entrepreneurship',
    emoji: '📈',
    tier: 'gold',
    estimated_cpm_range: '$14–$50',
    cpm: { min: 14, max: 50 },
    script_tone: 'motivational, strategic',
    hook_style: 'story_open',
    thumbnail_colors: { background: '#1e293b', primary_text: '#FFFFFF', accent: '#38BDF8', secondary: '#0369A1' },
    thumbnail_emotion: 'strategic, successful',
    voiceover_style: 'smooth, corporate, storytelling',
    music_mood: 'inspirational corporate, building climax',
    stock_keywords: ['startup', 'side hustle', 'business tips', 'entrepreneur'],
    image_prompt_style: 'modern skyscraper glass, cinematic office, blue steel tones',
    title_formula: 'How [Company] Fooled the World and Made $Billion',
    recommended_duration: '8-15 minutes',
    recommendedDuration: [480, 900],
    recommended_upload_time: 'Tuesday 1PM EST',
    platforms: { youtube: { score: 10, note: "Strong for long-form" }, tiktok: { score: 6, note: "Hooks work, depth less" } },
    bestStyles: ["cinematic", "whiteboard", "documentary"],
    avoidStyles: ["ghibli", "paper_craft"],
    hookFormulas: ["story_open", "bold_claim", "curiosity_gap"],
    keywords: ["startup", "side hustle", "business tips", "entrepreneur"],
    monetization: ["AdSense", "course sales", "mastermind"],
    contentPillars: ["case studies", "how to start", "business mistakes", "entrepreneur stories", "startup funding", "growing to 7 figures", "business models", "marketing strategies", "dropshipping", "Amazon FBA", "agency business", "social media business"],
    audience: { age: "22–45", intent: "very high", retention: "high" },
    competitionLevel: "very high"
  },
  {
    niche_id: 'productivity',
    display_name: 'Productivity & Tools',
    emoji: '⚡',
    tier: 'gold',
    estimated_cpm_range: '$12–$40',
    cpm: { min: 12, max: 40 },
    script_tone: 'practical, clean',
    hook_style: 'curiosity_gap',
    thumbnail_colors: { background: '#fafafa', primary_text: '#000000', accent: '#F43F5E', secondary: '#9F1239' },
    thumbnail_emotion: 'clean, focused',
    voiceover_style: 'upbeat, crisp, fast-paced',
    music_mood: 'lo-fi hip hop, chillwork',
    stock_keywords: ['Notion', 'productivity', 'time management', 'workflow'],
    image_prompt_style: 'aesthetic unboxing style desk setup, bright natural light, minimalist',
    title_formula: 'My [System] That Guarantees [Result] Every Day',
    recommended_duration: '5-10 minutes',
    recommendedDuration: [300, 600],
    recommended_upload_time: 'Monday 10AM EST',
    platforms: { youtube: { score: 9, note: "Tutorial format thrives" }, shorts: { score: 8, note: "Quick tip format" } },
    bestStyles: ["whiteboard", "infographic", "cinematic"],
    avoidStyles: ["dark_noir", "ghibli"],
    hookFormulas: ["curiosity_gap", "question_hook", "bold_claim"],
    keywords: ["Notion", "productivity", "time management", "workflow"],
    monetization: ["AdSense", "SaaS affiliate", "template sales"],
    contentPillars: ["tool reviews", "systems", "morning routines", "desk setups", "Notion templates", "time management", "deep work", "focus hacks", "second brain", "weekly review", "anti-procrastination", "digital minimalism"],
    audience: { age: "22–40", intent: "high", retention: "high" },
    competitionLevel: "medium"
  },
  {
    niche_id: 'luxury',
    display_name: 'Luxury & Lifestyle',
    emoji: '💎',
    tier: 'gold',
    estimated_cpm_range: '$12–$42',
    cpm: { min: 12, max: 42 },
    script_tone: 'aspirational, relaxed',
    hook_style: 'story_open',
    thumbnail_colors: { background: '#111111', primary_text: '#EAB308', accent: '#FFFFFF', secondary: '#49423D' },
    thumbnail_emotion: 'exclusive, rich',
    voiceover_style: 'smooth, expensive-sounding, relaxed',
    music_mood: 'luxury lounge house, chillout pool',
    stock_keywords: ['luxury cars', 'designer', 'expensive', 'rich lifestyle'],
    image_prompt_style: 'gold luxury aesthetic, private jet interior, sparkling champagne',
    title_formula: 'Inside the $Billion Life of [Person/Location]',
    recommended_duration: '5-12 minutes',
    recommendedDuration: [300, 720],
    recommended_upload_time: 'Friday 3PM EST',
    platforms: { youtube: { score: 8, note: "Long vlogs work" }, reels: { score: 10, note: "Visual-first = perfect" }, tiktok: { score: 9, note: "Aspirational content viral" } },
    bestStyles: ["cinematic", "3d_render", "watercolor"],
    avoidStyles: ["whiteboard", "infographic", "stock_footage"],
    hookFormulas: ["story_open", "curiosity_gap", "pov_hook"],
    keywords: ["luxury cars", "designer", "expensive", "rich lifestyle"],
    monetization: ["brand deals", "AdSense", "affiliate (luxury)"],
    contentPillars: ["luxury reviews", "vlogs", "day in life", "comparisons", "luxury cars", "private jets", "designer fashion", "luxury watches", "5-star hotels", "rich neighborhoods", "billionaire lifestyle", "luxury tech"],
    audience: { age: "18–35", intent: "aspirational", retention: "medium" },
    competitionLevel: "medium"
  },
  {
    niche_id: 'health_wellness',
    display_name: 'Health & Wellness',
    emoji: '🍎',
    tier: 'silver',
    estimated_cpm_range: '$12–$40',
    cpm: { min: 12, max: 40 },
    script_tone: 'warm, credible',
    hook_style: 'fear_hook',
    thumbnail_colors: { background: '#064E3B', primary_text: '#FFFFFF', accent: '#A7F3D0', secondary: '#047857' },
    thumbnail_emotion: 'vibrant, energetic',
    voiceover_style: 'calming, enthusiastic, clear',
    music_mood: 'ambient meditation, gentle acoustic',
    stock_keywords: ['gut health', 'longevity', 'sleep', 'natural remedies'],
    image_prompt_style: 'fresh bright ingredients, sunlit kitchen, clean aesthetic',
    title_formula: 'What Happens to Your Body When You [Action] for [Time]',
    recommended_duration: '5-10 minutes',
    recommendedDuration: [300, 600],
    recommended_upload_time: 'Sunday 9AM EST',
    platforms: { youtube: { score: 8, note: "Evergreen" }, reels: { score: 9, note: "Before/after works" }, tiktok: { score: 9, note: "High shareability" } },
    bestStyles: ["cinematic", "watercolor", "pov"],
    avoidStyles: ["dark_noir", "3d_render", "infographic"],
    hookFormulas: ["fear_hook", "story_open", "bold_claim"],
    keywords: ["gut health", "longevity", "sleep", "natural remedies"],
    monetization: ["AdSense", "supplement affiliate", "course"],
    contentPillars: ["health tips", "research summaries", "wellness routines", "debunking myths", "gut health", "sleep optimization", "longevity secrets", "cold plunge & sauna", "supplements guide", "anti-aging", "natural remedies", "nutrition science"],
    audience: { age: "28–55", intent: "high", retention: "high" },
    competitionLevel: "very high"
  },
  {
    niche_id: 'weight_loss',
    display_name: 'Weight Loss & Fitness',
    emoji: '💪',
    tier: 'silver',
    estimated_cpm_range: '$10–$38',
    cpm: { min: 10, max: 38 },
    script_tone: 'energetic, motivational',
    hook_style: 'before_after',
    thumbnail_colors: { background: '#000000', primary_text: '#FFFFFF', accent: '#F97316', secondary: '#C2410C' },
    thumbnail_emotion: 'determined, energetic',
    voiceover_style: 'high energy, pushing, loud',
    music_mood: 'upbeat workout, synthwave, driven',
    stock_keywords: ['weight loss', 'workout', 'diet', 'gym', 'transformation'],
    image_prompt_style: 'high contrast gym lighting, sweat, intense action',
    title_formula: 'The Only [Topic] Routine You Need to Lose [Amount] in [Time]',
    recommended_duration: '3-8 minutes',
    recommendedDuration: [180, 480],
    recommended_upload_time: 'Monday 8AM EST',
    platforms: { youtube: { score: 8, note: "Tutorials + vlogs" }, reels: { score: 10, note: "Transformations viral" }, tiktok: { score: 9, note: "Workout clips viral" } },
    bestStyles: ["pov", "cinematic", "stock_footage"],
    avoidStyles: ["infographic", "whiteboard", "3d_render"],
    hookFormulas: ["before_after", "story_open", "bold_claim"],
    keywords: ["weight loss", "workout", "diet", "gym", "transformation"],
    monetization: ["AdSense", "fitness affiliate", "program sales"],
    contentPillars: ["workouts", "meal plans", "body transformations", "fat loss tips", "muscle building", "home workouts", "gym beginners", "diet comparisons", "calorie counting", "weight loss myths", "intermittent fasting", "6-pack abs"],
    audience: { age: "18–40", intent: "high", retention: "medium" },
    competitionLevel: "very high"
  },
  {
    niche_id: 'mental_health',
    display_name: 'Mental Health',
    emoji: '🧠',
    tier: 'silver',
    estimated_cpm_range: '$10–$35',
    cpm: { min: 10, max: 35 },
    script_tone: 'empathetic, gentle',
    hook_style: 'story_open',
    thumbnail_colors: { background: '#2e1065', primary_text: '#FFFFFF', accent: '#D8B4FE', secondary: '#4C1D95' },
    thumbnail_emotion: 'deep thought, realization',
    voiceover_style: 'soft, slow, empathetic',
    music_mood: 'soft sad piano, ambient sweeps',
    stock_keywords: ['anxiety', 'depression', 'therapy', 'mindfulness'],
    image_prompt_style: 'abstract mind concept, soft purple lighting, ethereal',
    title_formula: '[Number] Signs You Have [Hidden Condition] without Knowing',
    recommended_duration: '5-10 minutes',
    recommendedDuration: [300, 600],
    recommended_upload_time: 'Sunday 6PM EST',
    platforms: { youtube: { score: 9, note: "Deep content thrives" }, tiktok: { score: 8, note: "Vulnerable content viral" } },
    bestStyles: ["watercolor", "cinematic", "whiteboard"],
    avoidStyles: ["dark_noir", "pov", "3d_render"],
    hookFormulas: ["story_open", "question_hook", "empathy_hook"],
    keywords: ["anxiety", "depression", "therapy", "mindfulness"],
    monetization: ["AdSense", "app affiliate", "course"],
    contentPillars: ["coping tips", "mental health science", "personal stories", "therapy guides", "anxiety explained", "depression awareness", "trauma & healing", "narcissistic abuse", "impostor syndrome", "burnout recovery", "mindfulness", "dark psychology"],
    audience: { age: "18–40", intent: "medium", retention: "very high" },
    competitionLevel: "medium"
  },
  {
    niche_id: 'career',
    display_name: 'Career & Jobs',
    emoji: '💼',
    tier: 'silver',
    estimated_cpm_range: '$15–$45',
    cpm: { min: 15, max: 45 },
    script_tone: 'professional, practical',
    hook_style: 'fear_hook',
    thumbnail_colors: { background: '#0F172A', primary_text: '#FFFFFF', accent: '#10B981', secondary: '#047857' },
    thumbnail_emotion: 'confident, employed',
    voiceover_style: 'professional, guiding mentor',
    music_mood: 'subtle corporate background, positive',
    stock_keywords: ['resume', 'interview tips', 'job search', 'salary negotiation'],
    image_prompt_style: 'corporate glass office, confident handshake silhouette',
    title_formula: 'How to Pass Any [Role] Interview in [Year]',
    recommended_duration: '5-10 minutes',
    recommendedDuration: [300, 600],
    recommended_upload_time: 'Tuesday 2PM EST',
    platforms: { youtube: { score: 9, note: "Job seekers binge" }, shorts: { score: 8, note: "Resume tips perform" }, tiktok: { score: 7, note: "Office content works" } },
    bestStyles: ["cinematic", "whiteboard", "infographic"],
    avoidStyles: ["ghibli", "pov", "paper_craft"],
    hookFormulas: ["fear_hook", "bold_claim", "question_hook"],
    keywords: ["resume", "interview tips", "job search", "salary negotiation"],
    monetization: ["AdSense", "course sales", "resume service affiliate"],
    contentPillars: ["interview prep", "resume tips", "career growth", "salary negotiation", "remote jobs", "LinkedIn strategy", "job application mistakes", "high-paying careers", "career change", "freelancing", "work-life balance", "corporate red flags"],
    audience: { age: "22–40", intent: "high", retention: "high" },
    competitionLevel: "medium"
  },
  {
    niche_id: 'self_improvement',
    display_name: 'Self Improvement',
    emoji: '🌱',
    tier: 'silver',
    estimated_cpm_range: '$10–$35',
    cpm: { min: 10, max: 35 },
    script_tone: 'motivational, direct',
    hook_style: 'bold_claim',
    thumbnail_colors: { background: '#18181b', primary_text: '#FFFFFF', accent: '#EAB308', secondary: '#854D0E' },
    thumbnail_emotion: 'stoic, intense',
    voiceover_style: 'slow, deep, stoic, commanding',
    music_mood: 'dark ambient, cinematic drone',
    stock_keywords: ['habits', 'discipline', 'morning routine', 'mindset'],
    image_prompt_style: 'stoic marble statue, dark background, single light source, moody',
    title_formula: '[Number] Habits Keeping You Poor and Weak',
    recommended_duration: '5-12 minutes',
    recommendedDuration: [300, 720],
    recommended_upload_time: 'Sunday 10AM EST',
    platforms: { youtube: { score: 9, note: "List videos dominate" }, tiktok: { score: 8, note: "Tips content viral" }, shorts: { score: 9, note: "Daily habits format" } },
    bestStyles: ["cinematic", "whiteboard", "watercolor"],
    avoidStyles: ["dark_noir", "ghibli"],
    hookFormulas: ["bold_claim", "list_hook", "question_hook"],
    keywords: ["habits", "discipline", "morning routine", "mindset"],
    monetization: ["AdSense", "book affiliate", "course", "coaching"],
    contentPillars: ["habits", "mindset", "book summaries", "daily routines", "stoicism", "discipline tips", "confidence building", "fear & comfort zone", "social skills", "reading list", "journaling", "atomic habits"],
    audience: { age: "18–35", intent: "high", retention: "high" },
    competitionLevel: "very high"
  },
  {
    niche_id: 'motivation',
    display_name: 'Motivation & Mindset',
    emoji: '🔥',
    tier: 'silver',
    estimated_cpm_range: '$8–$30',
    cpm: { min: 8, max: 30 },
    script_tone: 'dramatic, intense',
    hook_style: 'bold_claim',
    thumbnail_colors: { background: '#000000', primary_text: '#FFFFFF', accent: '#DC2626', secondary: '#7F1D1D' },
    thumbnail_emotion: 'screaming success, aggressive',
    voiceover_style: 'loud, passionate, echoing',
    music_mood: 'epic orchestral, massive drums',
    stock_keywords: ['motivation', 'success mindset', 'hustle', 'discipline'],
    image_prompt_style: 'silhouetted winner in rain, neon red accents, extreme contrast',
    title_formula: 'WATCH THIS CURE YOUR LAZINESS - Motivation [Year]',
    recommended_duration: '1-5 minutes',
    recommendedDuration: [60, 300],
    recommended_upload_time: 'Monday 6AM EST',
    platforms: { youtube: { score: 7, note: "Compilations dominate" }, tiktok: { score: 9, note: "Short bursts go viral" }, shorts: { score: 10, note: "Top performer format" } },
    bestStyles: ["cinematic", "dark_noir", "stock_footage"],
    avoidStyles: ["whiteboard", "infographic", "ghibli"],
    hookFormulas: ["bold_claim", "story_open", "controversy"],
    keywords: ["motivation", "success mindset", "hustle", "discipline"],
    monetization: ["AdSense", "course affiliate", "merchandise"],
    contentPillars: ["motivational speeches", "quotes", "life lessons", "success stories", "overcoming failure", "hard work pays off", "millionaire mindset", "hustle culture", "morning motivation", "never give up", "elite mindset", "monk mentality"],
    audience: { age: "16–35", intent: "medium", retention: "medium" },
    competitionLevel: "very high"
  },
  {
    niche_id: 'relationships',
    display_name: 'Relationships & Psychology',
    emoji: '❤️',
    tier: 'silver',
    estimated_cpm_range: '$10–$32',
    cpm: { min: 10, max: 32 },
    script_tone: 'empathetic, insightful',
    hook_style: 'story_open',
    thumbnail_colors: { background: '#311226', primary_text: '#FFFFFF', accent: '#EC4899', secondary: '#9D174D' },
    thumbnail_emotion: 'dramatic, sad or happy',
    voiceover_style: 'soft, empathetic, engaging',
    music_mood: 'soft acoustic guitar, emotional piano',
    stock_keywords: ['dating', 'attachment style', 'toxic relationships', 'psychology'],
    image_prompt_style: 'moody cinematic lighting, silhouette couple, dramatic shadow',
    title_formula: '[Number] Signs They Are Secretly [Emotion/Behavior]',
    recommended_duration: '5-10 minutes',
    recommendedDuration: [300, 600],
    recommended_upload_time: 'Thursday 7PM EST',
    platforms: { youtube: { score: 8, note: "Deep dives popular" }, tiktok: { score: 10, note: "Relatable = viral" }, shorts: { score: 8, note: "Quick tips format" } },
    bestStyles: ["cinematic", "watercolor", "whiteboard"],
    avoidStyles: ["3d_render", "dark_noir", "infographic"],
    hookFormulas: ["story_open", "question_hook", "empathy_hook"],
    keywords: ["dating", "attachment style", "toxic relationships", "psychology"],
    monetization: ["AdSense", "therapy app affiliate", "course"],
    contentPillars: ["dating tips", "psychology facts", "red flags", "self-love", "attachment styles", "toxic relationships", "how to attract", "body language", "breakup recovery", "friendship dynamics", "family psychology", "manipulation tactics"],
    audience: { age: "18–35", intent: "medium", retention: "very high" },
    competitionLevel: "high"
  },
  {
    niche_id: 'history',
    display_name: 'History & Facts',
    emoji: '📜',
    tier: 'bronze',
    estimated_cpm_range: '$8–$25',
    cpm: { min: 8, max: 25 },
    script_tone: 'storytelling, cinematic',
    hook_style: 'shocking_stat',
    thumbnail_colors: { background: '#292524', primary_text: '#F5F5F4', accent: '#D97706', secondary: '#78350F' },
    thumbnail_emotion: 'mysterious, uncovering',
    voiceover_style: 'classic narrator, dramatic pauses',
    music_mood: 'orchestral suspense, classical',
    stock_keywords: ['history', 'ancient', 'war', 'forgotten facts', 'empires'],
    image_prompt_style: 'sepia toned old manuscript, dramatic lighting, volumetric dust',
    title_formula: 'The Dark History of [Topic] School Lied About',
    recommended_duration: '8-20 minutes',
    recommendedDuration: [480, 1200],
    recommended_upload_time: 'Saturday 12PM EST',
    platforms: { youtube: { score: 9, note: "Documentary style wins" }, shorts: { score: 8, note: "Surprising facts viral" }, tiktok: { score: 7, note: "Did you know format" } },
    bestStyles: ["documentary", "cinematic", "retro"],
    avoidStyles: ["3d_render", "watercolor", "paper_craft"],
    hookFormulas: ["shocking_stat", "curiosity_gap", "story_open"],
    keywords: ["history", "ancient", "war", "forgotten facts", "empires"],
    monetization: ["AdSense", "book affiliate", "Patreon"],
    contentPillars: ["untold stories", "wars", "empires", "mysteries", "ancient civilizations", "dark history", "historical figures", "lost cities", "WW2 secrets", "forgotten inventions", "timeline of events", "history myths debunked"],
    audience: { age: "25–55", intent: "low", retention: "very high" },
    competitionLevel: "medium"
  },
  {
    niche_id: 'true_crime',
    display_name: 'True Crime & Mystery',
    emoji: '🔍',
    tier: 'bronze',
    estimated_cpm_range: '$8–$28',
    cpm: { min: 8, max: 28 },
    script_tone: 'suspenseful, narrative',
    hook_style: 'story_open',
    thumbnail_colors: { background: '#000000', primary_text: '#FFFFFF', accent: '#B91C1C', secondary: '#7F1D1D' },
    thumbnail_emotion: 'terrified, mysterious',
    voiceover_style: 'low, whispery, suspenseful',
    music_mood: 'dark drone, heartbeat, scary',
    stock_keywords: ['unsolved', 'cold case', 'serial killer', 'mysterious disappearance'],
    image_prompt_style: 'dark alleyway, glowing crime tape, heavy rain, moody red lighting',
    title_formula: 'The Unsolved Case of the [Adjective] [Noun]',
    recommended_duration: '10-30 minutes',
    recommendedDuration: [600, 1800],
    recommended_upload_time: 'Friday 8PM EST',
    platforms: { youtube: { score: 10, note: "Massive loyal audiences" }, tiktok: { score: 7, note: "Short summaries work" } },
    bestStyles: ["dark_noir", "documentary", "cinematic"],
    avoidStyles: ["ghibli", "watercolor", "paper_craft"],
    hookFormulas: ["story_open", "curiosity_gap", "fear_hook"],
    keywords: ["unsolved", "cold case", "serial killer", "mysterious disappearance"],
    monetization: ["AdSense", "Patreon", "merch", "podcast cross-sell"],
    contentPillars: ["case breakdowns", "unsolved mysteries", "conspiracy theories", "forensics", "serial killers", "cold cases", "missing persons", "cults", "heists", "wrongful convictions", "FBI files", "paranormal & unexplained"],
    audience: { age: "25–50", intent: "low", retention: "very high" },
    competitionLevel: "high"
  },
  {
    niche_id: 'science',
    display_name: 'Science & Education',
    emoji: '🔬',
    tier: 'bronze',
    estimated_cpm_range: '$8–$22',
    cpm: { min: 8, max: 22 },
    script_tone: 'educational, wonder-driven',
    hook_style: 'shocking_stat',
    thumbnail_colors: { background: '#020617', primary_text: '#FFFFFF', accent: '#8B5CF6', secondary: '#4C1D95' },
    thumbnail_emotion: 'awe, confusion',
    voiceover_style: 'energetic, clear, inquisitive',
    music_mood: 'synth space ambient, curious',
    stock_keywords: ['how does it work', 'science explained', 'physics', 'biology'],
    image_prompt_style: 'glowing purple nebula, hyper-detailed cosmic dust, 8k',
    title_formula: 'What If [Extreme Scenario] Happened Tomorrow?',
    recommended_duration: '8-15 minutes',
    recommendedDuration: [480, 900],
    recommended_upload_time: 'Saturday 2PM EST',
    platforms: { youtube: { score: 10, note: "Explainer format king" }, shorts: { score: 7, note: "Mind-blowing facts" } },
    bestStyles: ["whiteboard", "3d_render", "infographic"],
    avoidStyles: ["pov", "stock_footage", "dark_noir"],
    hookFormulas: ["shocking_stat", "curiosity_gap", "question_hook"],
    keywords: ["how does it work", "science explained", "physics", "biology"],
    monetization: ["AdSense", "course affiliate", "Patreon"],
    contentPillars: ["explainers", "experiments", "debunking myths", "new discoveries", "space & astronomy", "human body science", "climate & earth", "quantum physics", "biology facts", "what if scenarios", "math explained", "chemistry reactions"],
    audience: { age: "15–40", intent: "low", retention: "very high" },
    competitionLevel: "medium"
  }
];
